stages:
- prepare
- build
- test

variables:
  DOCKER_FILE: Dockerfile
  DOCKER_TAG: latest
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}
  GIT_SUBMODULE_STRATEGY: normal
  FF_GITLAB_REGISTRY_HELPER_IMAGE: 1

.prepare:docker: &prepare_docker
  stage: prepare
  image:
    name: quay.io/buildah/stable
    name: docker
  before_script:
  - docker version
  - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
  - docker build -f ${DOCKER_FILE} -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
  - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  tags:
  - docker

prepare:docker:
  <<: *prepare_docker

build:kernel:
  stage: build
  image: ${CI_REGISTRY_IMAGE}
  script:
    - cargo build -Z build-std=core,alloc --no-default-features --target x86_64-eduos.json
  artifacts:
    paths:
      - target/x86_64-eduos/debug/eduos-rs

test:kernel:
   stage: test
   dependencies:
     - build:kernel
   image: ${CI_REGISTRY_IMAGE}
   script:
     - lscpu
     - kvm-ok
     - RUST_LOG=debug ehyve -f ./demo/hello target/x86_64-eduos/debug/eduos-rs
   tags:
     - privileged
