[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

[build]
target = "x86_64-eduos.json"

[target.x86_64-eduos]
runner = "bootimage runner"
