name: Build

on:
  push:
    branches:
      - stage2
  pull_request:
    branches:
      - stage2
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
         submodules: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Build
      run:
         cargo build -Z build-std=core,alloc --no-default-features --target x86_64-eduos.json
      continue-on-error: ${{ matrix.os == 'macOS-latest' }}
