name: Clippy

on:
  push:
    branches:
      - stage4
  pull_request:
    branches:
      - stage4

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v6
      with:
         submodules: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Check clippy (x86_64)
      run: cargo clippy
    - name: Check clippy (aarch64)
      run: cargo clippy --target aarch64-eduos.json
    - name: Check clippy (riscv64)
      run: cargo clippy --target riscv64-eduos.json
