name: Run

on:
  push:
    branches:
      - stage0
  pull_request:
    branches:
      - stage0
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]

    steps:
    - name: Install QEMU (ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install qemu-system-x86
    - name: Install QEMU (macos)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew update
        brew install qemu
    - name: Install QEMU (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install qemu
        echo "$Env:Programfiles\qemu" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
    - uses: actions/checkout@v4
      with:
         submodules: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Install bootimage
      run: cargo install bootimage
    - name: Build (x86_64)
      run:
         cargo build
    - name: Build (i686)
      run:
        cargo build --target=i686-eduos.json
    - name: run (ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: ./test.sh
    - name: run (macos)
      if: ${{ matrix.os == 'macos-latest' }}
      run: ./test.sh
    - name: run (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: pwsh -command ".\$GITHUB_WORKSPACE\test.ps1"

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Build release version (i686)
        run:
          cargo build --target=i686-eduos.json --release
      - name: Create artifacts
        run: |
          mkdir -p i686/stage0
          cp target/i686-eduos/release/eduos-rs i686/stage0/
      - uses: actions/upload-artifact@v4
        with:
          name: i686-stage0
          path: i686