name: Build

on:
  push:
    branches:
      - stage8
  pull_request:
    branches:
      - stage8
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]

    steps:
    - name: Install QEMU (ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install qemu-system-x86
    - name: Install QEMU (macos)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew update
        brew install qemu
    - name: Install QEMU (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install qemu
        echo "$Env:Programfiles\qemu" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
    - uses: actions/checkout@v4
      with:
         submodules: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Install bootimage
      run: cargo install bootimage
    - name: Build
      run:
         cargo build
    - name: run (ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: ./test.sh
    - name: run (macos)
      if: ${{ matrix.os == 'macos-latest' }}
      run: ./test.sh
    - name: run (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: pwsh -command ".\$GITHUB_WORKSPACE\test.ps1"
